# Generated by Django 4.1.13 on 2023-11-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
