# Generated by Django 4.2.7 on 2023-11-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(default=77, upload_to='receipe'),
        ),
    ]
