# Generated by Django 4.2.7 on 2023-11-17 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 11, 17, 11, 19, 57, 681111, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
