# Generated by Django 4.2.7 on 2023-11-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subject_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='SubjectMark',
        ),
    ]
