# Generated by Django 4.2.7 on 2023-11-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
    ]
